### ISSUE TITLE
sick_scan2 (ROS2 Driver) changes the factory default configs and makes it no longer runable with ROS1

### ISSUE THREAD

**Issue by Bmoradi93** [SICKAG/sick_scan2#16]
Hi all,
Recently, we have started our migration to ROS2 and we are using the sick_scan2 driver under Foxy version.
It turns out sick_scan2 driver somehow changes some default configs in the laser built-in software driver and makes it no longer runnable with the sick_scan1 (ROS1) driver. 
After using sick_scan2, one must reset the laser config in order to make it runnable with sick_scan2.
We are using [sick_tim_571](https://www.sick.com/ca/en/detection-and-ranging-solutions/2d-lidar-sensors/tim5xx/tim571-2050101/p/p412444) laser scanner in our robot. 
Any instructions will be appreciated. Thanks!
Errors are attached!
![Selection_437](https://user-images.githubusercontent.com/47978272/104949386-bb18ae00-5973-11eb-8ad6-05b4a7a8c63c.png)
![Selection_437](https://user-images.githubusercontent.com/47978272/104949394-be139e80-5973-11eb-9989-f41710e1d1df.png)
![Selection_436](https://user-images.githubusercontent.com/47978272/104949400-c075f880-5973-11eb-93fc-cab712ee92de.png)
![Selection_434](https://user-images.githubusercontent.com/47978272/104949407-c1a72580-5973-11eb-96c7-459880efea22.png)

**Comment by michael1309** [comment]
I guess this is a problem between binary mode and ascii mode. The lidar tries the configured mode at the beginning. If it can't be set (signaled by a timeout message), it will switch to the other mode. 

I recommend you to set the mode for the Lidar with SOPAS ET and store it in the EEPROM. You should then also set this mode in the launch files. The recommended mode is "Binary" (instead of ASCII).

Good luck!

**Comment by michael1309** [comment]
closed due to inactivity
